### ISSUE TITLE
TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread

### ISSUE THREAD

**Issue by AhmedKaram2** [shubham0204/FaceRecognition_With_FaceNet_Android#31]
FATAL EXCEPTION: main
                                                                                                    Process: com.ml.quaterion.facenetdetection, PID: 11467
                                                                                                    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
                                                                                                    Falling back to OpenGL
                                                                                                    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
                                                                                                    Node number 181 (TfLiteGpuDelegateV2) failed to invoke.
                                                                                                    	at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
                                                                                                    	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:249)
                                                                                                    	at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:133)
                                                                                                    	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:80)
                                                                                                    	at org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:126)
                                                                                                    	at org.tensorflow.lite.Interpreter.run(Interpreter.java:80)
                                                                                                    	at com.ml.quaterion.facenetdetection.model.FaceNetModel.runFaceNet(FaceNetModel.kt:87)
                                                                                                    	at com.ml.quaterion.facenetdetection.model.FaceNetModel.getFaceEmbedding(FaceNetModel.kt:79)
                                                                                                    	at com.ml.quaterion.facenetdetection.FileReader$getEmbedding$2.invokeSuspend(FileReader.kt:108)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a0c68f4, Dispatchers.Main]

**Comment by denny-zefanya** [comment]
I try this [https://stackoverflow.com/questions/71485371/android-12api-level-31-tflitegpudelegate-invoke-gpudelegate-must-run-on-the](url)
I add these lines to AndroidManifest to fix it:
        <uses-native-library
            android:name="libOpenCL.so"
            android:required="false" />

        <uses-native-library
            android:name="libOpenCL-car.so"
            android:required="false" />

        <uses-native-library
            android:name="libOpenCL-pixel.so"
            android:required="false" />

**Comment by shubham0204** [comment]
@AhmedKaram2 Did you try the solution suggested by @denny-zefanya?

**Comment by AhmedKaram2** [comment]
yes and it's working now thanks @denny-zefanya @shubham0204
